version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Entered the build phase
      - dotnet build one
      - ls one/out
      - find one
  post_build:
    commands:
      - echo Entered the post_build phase
      - echo Run unit tests
      - dotnet build one.ut
      - dotnet test one.ut
artifacts:
  files:
    - 'one/out/**/*'
  discard-paths: yes