version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Entered the build phase
      - docker build -t `date "+%Y-%m-%d_%H-%M-%S"` one
  post_build:
    commands:
      - echo Nothing to do in the post_build phase
